___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy.random import randn
np.random.seed(101)

In [4]:
randn(5,4)

array([[ 0.30266545,  1.69372293, -1.70608593, -1.15911942],
       [-0.13484072,  0.39052784,  0.16690464,  0.18450186],
       [ 0.80770591,  0.07295968,  0.63878701,  0.3296463 ],
       [-0.49710402, -0.7540697 , -0.9434064 ,  0.48475165],
       [-0.11677332,  1.9017548 ,  0.23812696,  1.99665229]])

In [7]:
pd.DataFrame(randn(5,4),['A', 'B', 'C', 'D' ,'E'],['W', 'X' ,'Y' ,'Z'])

          W         X         Y         Z
A -1.467514 -0.494095 -0.162535  0.485809
B  0.392489  0.221491 -0.855196  1.541990
C  0.666319 -0.538235 -0.568581  1.407338
D  0.641806 -0.905100 -0.391157  1.028293
E -1.972605 -0.866885  0.720788 -1.223082

In [5]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [8]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [9]:
df['W']

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

In [10]:
type(df['W'])

pandas.core.series.Series

In [11]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A -0.993263  0.000366
B  1.025984  0.649826
C  2.154846 -0.346419
D  0.147027  1.024810
E -0.925874  0.610478

In [12]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: W, dtype: float64

DataFrame Columns are just Series

In [13]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [14]:
df['new'] = df['W'] + df['Y']

In [15]:
df

          W         X         Y         Z       new
A -0.993263  0.196800 -1.136645  0.000366 -2.129908
B  1.025984 -0.156598 -0.031579  0.649826  0.994405
C  2.154846 -0.610259 -0.755325 -0.346419  1.399521
D  0.147027 -0.479448  0.558769  1.024810  0.705796
E -0.925874  1.862864 -1.133817  0.610478 -2.059691

** Removing Columns**

In [16]:
df.drop('new',axis=1)

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [17]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A -0.993263  0.196800 -1.136645  0.000366 -2.129908
B  1.025984 -0.156598 -0.031579  0.649826  0.994405
C  2.154846 -0.610259 -0.755325 -0.346419  1.399521
D  0.147027 -0.479448  0.558769  1.024810  0.705796
E -0.925874  1.862864 -1.133817  0.610478 -2.059691

In [18]:
df.drop('new',axis=1,inplace=True)

In [19]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

Can also drop rows this way:

In [20]:
df.drop('E',axis=0)

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [21]:
df.shape

(5, 4)

In [27]:
df[['Z','X']]

          Z         X
A  0.000366  0.196800
B  0.649826 -0.156598
C -0.346419 -0.610259
D  1.024810 -0.479448
E  0.610478  1.862864

** Selecting Rows**

In [28]:
df.loc['B']

W    1.025984
X   -0.156598
Y   -0.031579
Z    0.649826
Name: B, dtype: float64

In [29]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

Or select based off of position instead of label

In [30]:
df.iloc[2]

W    2.154846
X   -0.610259
Y   -0.755325
Z   -0.346419
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [31]:
df.loc['B','Y']

np.float64(-0.031579143908112575)

In [32]:
df.loc[['A','B'],['W','Y']]

          W         Y
A -0.993263 -1.136645
B  1.025984 -0.031579

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [33]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [34]:
df>0

       W      X      Y      Z
A  False   True  False   True
B   True  False  False   True
C   True  False  False  False
D   True  False   True   True
E  False   True  False   True

In [35]:
df[df>0]

          W         X         Y         Z
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [37]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [38]:
df['W']>0

A    False
B     True
C     True
D     True
E    False
Name: W, dtype: bool

In [36]:
df[df['W']>0]

          W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [39]:
df[df['W']>0]['Y']

B   -0.031579
C   -0.755325
D    0.558769
Name: Y, dtype: float64

In [40]:
df[df['W']>0][['Y','X']]

          Y         X
B -0.031579 -0.156598
C -0.755325 -0.610259
D  0.558769 -0.479448

In [42]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

For two conditions you can use | and & with parenthesis:

In [45]:
df[(df['W']>0) & (df['Y'] > 0.5)]

          W         X         Y        Z
D  0.147027 -0.479448  0.558769  1.02481

In [46]:
df[(df['W']>0) | (df['Y'] > 0.5)]

          W         X         Y         Z
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [47]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [48]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A -0.993263  0.196800 -1.136645  0.000366
1     B  1.025984 -0.156598 -0.031579  0.649826
2     C  2.154846 -0.610259 -0.755325 -0.346419
3     D  0.147027 -0.479448  0.558769  1.024810
4     E -0.925874  1.862864 -1.133817  0.610478

In [49]:
df

          W         X         Y         Z
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [51]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [52]:
df['States'] = newind

In [53]:
df

          W         X         Y         Z States
A -0.993263  0.196800 -1.136645  0.000366     CA
B  1.025984 -0.156598 -0.031579  0.649826     NY
C  2.154846 -0.610259 -0.755325 -0.346419     WY
D  0.147027 -0.479448  0.558769  1.024810     OR
E -0.925874  1.862864 -1.133817  0.610478     CO

In [54]:
df.set_index('States')

               W         X         Y         Z
States
CA     -0.993263  0.196800 -1.136645  0.000366
NY      1.025984 -0.156598 -0.031579  0.649826
WY      2.154846 -0.610259 -0.755325 -0.346419
OR      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478

In [55]:
df

          W         X         Y         Z States
A -0.993263  0.196800 -1.136645  0.000366     CA
B  1.025984 -0.156598 -0.031579  0.649826     NY
C  2.154846 -0.610259 -0.755325 -0.346419     WY
D  0.147027 -0.479448  0.558769  1.024810     OR
E -0.925874  1.862864 -1.133817  0.610478     CO

In [57]:
df.set_index('States',inplace=True)

In [58]:
df

               W         X         Y         Z
States
CA     -0.993263  0.196800 -1.136645  0.000366
NY      1.025984 -0.156598 -0.031579  0.649826
WY      2.154846 -0.610259 -0.755325 -0.346419
OR      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [253]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [254]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [257]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.153661  0.167638
   2 -0.765930  0.962299
   3  0.902826 -0.537909
G2 1 -1.549671  0.435253
   2  1.259904 -0.447898
   3  0.266207  0.412580

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [260]:
df.loc['G1']

          A         B
1  0.153661  0.167638
2 -0.765930  0.962299
3  0.902826 -0.537909

In [263]:
df.loc['G1'].loc[1]

A    0.153661
B    0.167638
Name: 1, dtype: float64

In [265]:
df.index.names

FrozenList([None, None])

In [266]:
df.index.names = ['Group','Num']

In [267]:
df

                  A         B
Group Num
G1    1    0.153661  0.167638
      2   -0.765930  0.962299
      3    0.902826 -0.537909
G2    1   -1.549671  0.435253
      2    1.259904 -0.447898
      3    0.266207  0.412580

In [270]:
df.xs('G1')

            A         B
Num
1    0.153661  0.167638
2   -0.765930  0.962299
3    0.902826 -0.537909

In [271]:
df.xs(['G1',1])

A    0.153661
B    0.167638
Name: (G1, 1), dtype: float64

In [273]:
df.xs(1,level='Num')

              A         B
Group
G1     0.153661  0.167638
G2    -1.549671  0.435253

# Great Job!