___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

In [ ]:
#%pip install sqlalchemy
#%pip install lxml
#%pip install html5lib
#%pip install BeautifulSoup4
#%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

# Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:
* CSV
* Excel
* HTML
* SQL

In [1]:
import numpy as np
import pandas as pd

In [9]:
pwd

'c:\\Udemy_Course\\DataScience\\projects\\03-Python-Pandas'

## CSV

### CSV Input

In [2]:
df = pd.read_csv('example')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### CSV Output

In [8]:
df.to_csv('example',index=False)
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

### Excel Input

In [14]:
pd.read_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### Excel Output

In [16]:
df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [17]:
df.to_csv('csv_output.csv', index=False)

In [19]:
pd.read_csv('csv_output.csv')

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

## HTML

You may need to install htmllib5,lxml, and BeautifulSoup4. In your terminal/command prompt run:

    conda install lxml
    conda install html5lib
    conda install BeautifulSoup4

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

Pandas can read table tabs off of html. For example:

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

In [20]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [22]:
type(df)

list

In [34]:
df

[                                          Bank Name               City  \
 0                       Tioga-Franklin Savings Bank       Philadelphia
 1                               Small Business Bank             Lenexa
 2     Kentland Federal Savings and Loan Association           Kentland
 3           Community Bank and Trust - West Georgia           LaGrange
 4                 Metropolitan Capital Bank & Trust            Chicago
 5                      The Santa Anna National Bank         Santa Anna
 6                              Pulaski Savings Bank            Chicago
 7                The First National Bank of Lindsay            Lindsay
 8             Republic First Bank dba Republic Bank       Philadelphia
 9                                     Citizens Bank           Sac City
 10                         Heartland Tri-State Bank            Elkhart
 11                              First Republic Bank      San Francisco
 12                                   Signature Bank           New York
 13                              Silicon Valley Bank        Santa Clara
 14                                Almena State Bank             Almena
 15                       First City Bank of Florida  Fort Walton Beach
 16                             The First State Bank      Barboursville
 17                               Ericson State Bank            Ericson
 18                 City National Bank of New Jersey             Newark
 19                                    Resolute Bank             Maumee
 20                            Louisa Community Bank             Louisa
 21                             The Enloe State Bank             Cooper
 22              Washington Federal Bank for Savings            Chicago
 23  The Farmers and Merchants State Bank of Argonia            Argonia
 24                              Fayette County Bank         Saint Elmo

             State   Cert                              Acquiring Institution  \
 0    Pennsylvania  33802  Second Federal Savings and Loan Association of...
 1          Kansas  25744           The Farmers State Bank of Oakley, Kansas
 2         Indiana  28722                                      Kentland Bank
 3         Georgia  25796                                        Anchor Bank
 4        Illinois  57488                            First Independence Bank
 5           Texas   5520                          Coleman County State Bank
 6        Illinois  28611                                    Millennium Bank
 7        Oklahoma   4134                             First Bank & Trust Co.
 8    Pennsylvania  27332                  Fulton Bank, National Association
 9            Iowa   8758                          Iowa Trust & Savings Bank
 10         Kansas  25851                             Dream First Bank, N.A.
 11     California  59017                          JPMorgan Chase Bank, N.A.
 12       New York  57053                                Flagstar Bank, N.A.
 13     California  24735                First–Citizens Bank & Trust Company
 14         Kansas  15426                                        Equity Bank
 15        Florida  16748                          United Fidelity Bank, fsb
 16  West Virginia  14361                                     MVB Bank, Inc.
 17       Nebraska  18265                         Farmers and Merchants Bank
 18     New Jersey  21111                                    Industrial Bank
 19           Ohio  58317                                 Buckeye State Bank
 20       Kentucky  58112                  Kentucky Farmers Bank Corporation
 21          Texas  10716                                 Legend Bank, N. A.
 22       Illinois  30570                                 Royal Savings Bank
 23         Kansas  17719                                        Conway Bank
 24       Illinois   1802                          United Fidelity Bank, fsb

          Closing Date  Fund  Sort ascending
 0     August 21, 2026                 10554
 1       July 17, 2026                 10553
 2       July 10, 2026                 10552
 3         May 1, 2026                 10551
 4    January 30, 2026                 10550
 5       June 27, 2025                 10549
 6    January 17, 2025                 10548
 7    October 18, 2024                 10547
 8      April 26, 2024                 10546
 9    November 3, 2023                 10545
 10      July 28, 2023                 10544
 11        May 1, 2023                 10543
 12     March 12, 2023                 10540
 13     March 10, 2023                 10539
 14   October 23, 2020                 10538
 15   October 16, 2020                 10537
 16      April 3, 2020                 10536
 17  February 14, 2020                 10535
 18   November 1, 2019                 10534
 19   October 25, 2019                 10533
 20   October 25, 2019                 10532
 21       May 31, 2019                 10531
 22  December 15, 2017                 10530
 23   October 13, 2017                 10529
 24       May 26, 2017                 10528  ]

In [21]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528

____

In [24]:
df[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550

_____
_____
# SQL (Optional)

* Note: If you are completely unfamiliar with SQL you can check out my other course: "Complete SQL Bootcamp" to learn SQL.

The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. For SQLite this is included in Python’s standard library by default. You can find an overview of supported drivers for each SQL dialect in the SQLAlchemy docs.


If SQLAlchemy is not installed, a fallback is only provided for sqlite (and for mysql for backwards compatibility, but this is deprecated and will be removed in a future version). This mode requires a Python database adapter which respect the Python DB-API.

See also some cookbook examples for some advanced strategies.

The key functions are:

* read_sql_table(table_name, con[, schema, ...])	
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])	
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])	
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, flavor, ...])	
    * Write records stored in a DataFrame to a SQL database.

In [28]:
%pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\user\anaconda3\envs\streamlitenv\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\user\anaconda3\envs\streamlitenv\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\anaconda3\envs\streamlitenv\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [29]:
from sqlalchemy import create_engine

In [30]:
engine = create_engine('sqlite:///:memory:')

In [35]:
df = pd.DataFrame(df[0])

In [36]:
df.to_sql('data', engine,  if_exists='append', index=False)

25

In [37]:
sql_df = pd.read_sql('data',con=engine)

In [38]:
sql_df

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528

In [40]:
df.to_sql('my_data', engine)

25

In [41]:
sql_index = pd.read_sql('my_data',con=engine)

In [42]:
sql_index

,index,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528

# Great Job!